using System;using System.IO;using System.Linq;using UnityEngine;using UnityEditor;using UnityEngine.Rendering;using UnityEngine.Rendering.Universal;
public static class WeddingCameraAudit {
public static void Run(){
var lines=new System.Collections.Generic.List<string>();lines.Add("ColorSpace="+QualitySettings.activeColorSpace+" Pipeline="+GraphicsSettings.currentRenderPipeline);
foreach(var sv in SceneView.sceneViews.Cast<SceneView>()){var c=sv.camera;var a=c.GetUniversalAdditionalCameraData();lines.Add("SceneView "+sv.titleContent.text+" lighting="+sv.sceneLighting+" effects="+sv.sceneViewState.showImageEffects+" HDR="+c.allowHDR+" postProcess="+a.renderPostProcessing+" volumeMask="+a.volumeLayerMask+" tonemapping="+a.antialiasing);}
foreach(var c in UnityEngine.Object.FindObjectsByType<Camera>(FindObjectsInactive.Include,FindObjectsSortMode.None)){if(c.cameraType==CameraType.SceneView)continue;var a=c.GetUniversalAdditionalCameraData();lines.Add("Camera "+c.name+" type="+c.cameraType+" enabled="+c.enabled+" HDR="+c.allowHDR+" postProcess="+a.renderPostProcessing+" volumeMask="+a.volumeLayerMask);}
foreach(var v in UnityEngine.Object.FindObjectsByType<Volume>(FindObjectsInactive.Include,FindObjectsSortMode.None)){lines.Add("Volume "+v.name+" active="+v.isActiveAndEnabled+" global="+v.isGlobal+" weight="+v.weight+" layer="+v.gameObject.layer);var p=v.sharedProfile;if(p==null)continue;foreach(var comp in p.components){lines.Add("  "+comp.GetType().Name+" active="+comp.active);foreach(var f in comp.GetType().GetFields()){var val=f.GetValue(comp) as VolumeParameter;if(val==null||!val.overrideState)continue;var prop=val.GetType().GetProperty("value");lines.Add("    "+f.Name+"="+prop?.GetValue(val));}}}
Directory.CreateDirectory(@"C:\Users\Pc\Documents\Codex\2026-10-02\blender-1-windows-pc-blender-blender\outputs\camera_audit");File.WriteAllLines(@"C:\Users\Pc\Documents\Codex\2026-10-02\blender-1-windows-pc-blender-blender\outputs\camera_audit\settings.txt",lines);
}}
