using UnityEditor;using UnityEngine;using UnityEngine.Rendering;using UnityEngine.Rendering.Universal;using System.IO;using System.Linq;
public static class WeddingCameraCompare {
public static void Run(){
const string Out=@"C:\Users\Pc\Documents\Codex\2026-10-02\blender-1-windows-pc-blender-blender\outputs\camera_audit";
var root=GameObject.Find("BrideNPC");var f=root.GetComponentsInChildren<MeshFilter>().First(x=>AssetDatabase.GetAssetPath(x.sharedMesh).EndsWith("Bride_Tripo.fbx"));
var obj=new GameObject("~CameraComparison"){hideFlags=HideFlags.HideAndDontSave};var cam=obj.AddComponent<Camera>();var data=cam.GetUniversalAdditionalCameraData();data.volumeLayerMask=~0;
var rt=new RenderTexture(1200,1200,24);var prev=RenderTexture.active;var volume=UnityEngine.Object.FindObjectsByType<Volume>(FindObjectsInactive.Exclude,FindObjectsSortMode.None).First(v=>v.isGlobal);var original=volume.profile;var clone=ScriptableObject.CreateInstance<VolumeProfile>();foreach(var c in original.components)clone.components.Add(Object.Instantiate(c));
try{cam.targetTexture=rt;cam.nearClipPlane=.01f;cam.farClipPlane=100;cam.fieldOfView=25;cam.allowHDR=true;var target=f.transform.TransformPoint(new Vector3(0,1.115f,.12f));var scale=f.transform.TransformVector(Vector3.up).magnitude;cam.transform.position=target+root.transform.forward*scale*1.8f;cam.transform.LookAt(target);
foreach(var mode in new[]{"capture_no_post","main_post","post_without_lut","post_without_tone","post_without_both"}){data.renderPostProcessing=mode!="capture_no_post";volume.profile=mode.StartsWith("post_without")?clone:original;if(clone.TryGet<ColorLookup>(out var lut))lut.contribution.value=mode=="post_without_lut"||mode=="post_without_both"?0:1;if(clone.TryGet<Tonemapping>(out var tone))tone.mode.value=mode=="post_without_tone"||mode=="post_without_both"?TonemappingMode.None:TonemappingMode.Neutral;VolumeManager.instance.Update(cam.transform,data.volumeLayerMask);cam.Render();RenderTexture.active=rt;var tex=new Texture2D(1200,1200,TextureFormat.RGB24,false);tex.ReadPixels(new Rect(0,0,1200,1200),0,0);tex.Apply();File.WriteAllBytes(Out+"/"+mode+".png",tex.EncodeToPNG());Object.DestroyImmediate(tex);}
}finally{volume.profile=original;RenderTexture.active=prev;cam.targetTexture=null;Object.DestroyImmediate(rt);Object.DestroyImmediate(obj);foreach(var c in clone.components)Object.DestroyImmediate(c);Object.DestroyImmediate(clone);}
}}
